// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReadingChallengeApi;

namespace ReadingChallengeApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210502014145_Migration001")]
    partial class Migration001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("ReadingChallengeApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmazonLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("ReadingChallengeApi.Models.Prompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PromptBookId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PromptBookId");

                    b.ToTable("Prompts");
                });

            modelBuilder.Entity("ReadingChallengeApi.Models.PromptBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BookReadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateRead")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookReadId");

                    b.ToTable("PromptBooks");
                });

            modelBuilder.Entity("ReadingChallengeApi.Models.Prompt", b =>
                {
                    b.HasOne("ReadingChallengeApi.Models.PromptBook", null)
                        .WithMany("Prompts")
                        .HasForeignKey("PromptBookId");
                });

            modelBuilder.Entity("ReadingChallengeApi.Models.PromptBook", b =>
                {
                    b.HasOne("ReadingChallengeApi.Models.Book", "BookRead")
                        .WithMany()
                        .HasForeignKey("BookReadId");

                    b.Navigation("BookRead");
                });

            modelBuilder.Entity("ReadingChallengeApi.Models.PromptBook", b =>
                {
                    b.Navigation("Prompts");
                });
#pragma warning restore 612, 618
        }
    }
}
